# Generated by Django 5.0.2 on 2024-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "An item with this name already exists."
                        },
                        help_text="Items's name",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        error_messages={
                            "unique": "An Item with this description already exists."
                        },
                        help_text="Item's description",
                        max_length=700,
                        unique=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Item's price",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
            },
        ),
    ]
