# Generated by Django 5.0.2 on 2024-03-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderToItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="The quantity of the product in the order",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item that is in the order.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_to_items",
                        to="items.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order in which the item is.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_to_items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order to item",
                "verbose_name_plural": "order to items",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                help_text="Order items.",
                related_name="orders",
                through="orders.OrderToItem",
                to="items.item",
                verbose_name="items",
            ),
        ),
    ]
